name: Run Tests
on: [push]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Clojure deps
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.3
        with:
          path: |
            ~/.gitlibs
            ~/.m2/repository
          key: ${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Install Clojure
        uses: DeLaGuardo/setup-clojure@e6e77cdf6873b7af18609cf29f24bee054c5be72 # 13.5.3
        with:
          cli: latest

      - name: Run tests
        run: clojure -M:test
